### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Deanius97** [atanasyanew/media-server#4]
First of all, thank you for creating this docker compose file with explanation! 

I tried to install it today, but I keep getting the following error:
<img width="634" alt="Screenshot 2024-01-21 at 12 29 53" src="https://github.com/atanasyanew/media-server/assets/124905108/6dd13bb5-57d3-4af3-9f2d-86bd78fc7c52">
<img width="637" alt="Screenshot 2024-01-21 at 12 30 00" src="https://github.com/atanasyanew/media-server/assets/124905108/6aef00e5-9994-4c4b-8f39-691fb13d4ac0">

Any idea what I am doing wrong or how to fix this?

Big thanks in advance!

Daan

**Comment by Deanius97** [comment]
Seems that every program needed an individual folder, before starting the container. After that I only have one error remaining:
<img width="590" alt="Screenshot 2024-01-21 at 12 55 12" src="https://github.com/atanasyanew/media-server/assets/124905108/e07c73a3-0b47-456c-bd10-88ac1e882109">

Any idea how to solve this issue?

**Comment by atanasyanew** [comment]
Already something running on port?

**Comment by Deanius97** [comment]
The error stated TCP port 443 and 80. Can't find anything that is connected via the same ports.

**Comment by Deanius97** [comment]
Seems that is is a know error with port 80 and 443. Hereby the article I found that states to change these values to:

"... In the Port Settings section, change the Auto port for 443 to 8081 and the Auto port for 80 to 8080. NOTE: If you are using these ports for anything else on your Synology NAS, you will have to use different ports."
[https://www.wundertech.net/how-to-setup-heimdall-on-a-synology-nas/](url)
